/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: f917d736dc087900a0b06d5578932697)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	AI_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
	AUTH_SEND_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	ADMIN_EMAIL: "zhumo0110@gmail.com";
	RESEND_FROM_EMAIL: "星月塔罗 <login@mail.tarot.zxkpg.uk>";
	DEEPSEEK_API_KEY: string;
	RESEND_API_KEY: string;
	AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_EMAIL" | "RESEND_FROM_EMAIL" | "DEEPSEEK_API_KEY" | "RESEND_API_KEY" | "AUTH_SECRET">> {}
}
